version: '3.1'

services:
  db-test:
    image: postgres
    restart: always
    env_file:
      - .env.test
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-test:/var/lib/postgresql/data

volumes:
  postgres-data-test:
